version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/examples"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5

# Disabled because RN breaks way to often when random packages update
# and I don't want to deal with updating it
# - package-ecosystem: npm
#   directory: "/examples/react-native"
#   schedule:
#     interval: weekly
#   open-pull-requests-limit: 5
