version: 2
updates:
    - package-ecosystem: "github-actions"
      directory: "/"
      schedule:
        interval: "daily"
      open-pull-requests-limit: 10
      secrets:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: monthly
      open-pull-requests-limit: 10
      versioning-strategy: increase
      ignore:
          # For all packages, ignore all minor & patch updates
          - dependency-name: "*"
            update-types:
                ["version-update:semver-minor", "version-update:semver-patch"]
    - package-ecosystem: npm
      directory: "packages/cryptography"
      schedule:
          interval: monthly
      open-pull-requests-limit: 10
      versioning-strategy: increase
      ignore:
          # For all packages, ignore all minor & patch updates
          - dependency-name: "*"
            update-types:
                ["version-update:semver-minor", "version-update:semver-patch"]
    - package-ecosystem: npm
      directory: "packages/proto"
      schedule:
          interval: monthly
      open-pull-requests-limit: 10
      versioning-strategy: increase
      ignore:
          # For all packages, ignore all minor & patch updates
          - dependency-name: "*"
            update-types:
                ["version-update:semver-minor", "version-update:semver-patch"]
    - package-ecosystem: npm
      directory: "/examples"
      schedule:
          interval: monthly
      open-pull-requests-limit: 5
      versioning-strategy: increase
      ignore:
          # For all packages, ignore all minor & patch updates
          - dependency-name: "*"
            update-types:
                ["version-update:semver-minor", "version-update:semver-patch"]
    - package-ecosystem: npm
      directory: "/examples/react-native-example"
      schedule:
          interval: monthly
      open-pull-requests-limit: 5
      versioning-strategy: increase
      ignore:
          # For all packages, ignore all minor & patch updates
          - dependency-name: "*"
            update-types:
                ["version-update:semver-minor", "version-update:semver-patch"]
