version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/examples"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
- package-ecosystem: npm
  directory: "/examples/react-native"
  schedule:
    interval: weekly
  open-pull-requests-limit: 5

