version: "3"

silent: true

tasks:
    default:
        deps:
            - build

    docs:
        cmds:
            - npx typedoc
              --excludeInternal
              --excludePrivate
              --excludeProtected
              --out docs
              --validation.invalidLink
              --entryPoints src/index.js src/browser.js src/native.js

    install:
        cmds:
            - pnpm i > /dev/null 2>&1

    build:
        deps:
            - install
        cmds:
            - task: format
            - task: lint
            - npx babel src -d lib --out-file-extension .cjs > /dev/null
            - npx yalc publish > /dev/null

    clean:
        cmds:
            - rm -rf node_modules

    format:
        cmds:
            - npx prettier src "test/unit/*.js" "*.json" "src/*.js" --write > /dev/null

    lint:
        deps:
            - "lint:types"
            - "lint:dpdm"
            - "lint:format"
            - "lint:js"

    "lint:types":
        cmds:
            - npx tsc

    "lint:dpdm":
        cmds:
            # It's really annoying seeing [X/X] Analyze done. If a circular dep is found remove `2>&1`
            - npx dpdm src/index.js --circular true --tree false --warning false > /dev/null 2>&1

    "lint:format":
        cmds:
            - npx prettier src "test/unit/*.js" "*.json" "src/*.js" --check > /dev/null

    "lint:js":
        cmds:
            - npx eslint --fix "src/**/*.js" "test/unit/**/*.js"

    "test:release":
        cmds:
            - task: build
            - task: test:unit

    test:
        deps:
            - "test:unit"

    "test:unit":
        deps:
            - "test:unit:node"
            - "test:unit:browser"

    "test:unit:node":
        cmds:
            - npx mocha --inline-diffs -r @babel/register -r chai/register-expect.js "test/unit/*.js" --timeout 120000 {{.CLI_ARGS}}

    "test:unit:codecov":
        cmds:
            - npx c8 --reporter=lcov --reporter=text-summary ./node_modules/.bin/mocha --inline-diffs -r @babel/register -r chai/register-expect.js "test/unit/*.js" --timeout 120000 {{.CLI_ARGS}}
            - npx c8 report

    "test:unit:browser":
        cmds:
            - ./scripts/browser_test.sh

    update:
        cmds:
            - task: build

    publish:
        preconditions:
            - '! grep ''".*": "link:.*"'' package.json > /dev/null'
        deps:
            - "test:release"
        cmds:
            - pnpm publish {{.CLI_ARGS}}
