export PATH := "./node_modules/.bin:" + env_var('PATH')

default:
    just --choose

install:
    pnpm i

build: install format lint

lint: install lint-types lint-format lint-js

lint-types:
    tsc

lint-format:
    prettier "*.json" "src/*.js" --check > /dev/null

lint-js:
    eslint --fix "src/**/*.js"

format:
    prettier "*.json" "src/*.js" --write > /dev/null

clean:
    rm -rf node_modules
