version: "3"

silent: true

tasks:
    default:
        deps:
            - build

    docs:
        cmds:
            - npx typedoc
                --excludeInternal 
                --excludePrivate 
                --excludeProtected 
                --out docs 
                --validation.invalidLink 
                --entryPoints src/index.js src/browser.js src/native.js

    "install:submodules":
        cmds:
            # TODO: How do we support this build step when we update the
            # protobufs? Currently, this step results in reseting any protobuf
            # updates we may have.
            #- git submodule update --init
            # using tag --remote in order to always apply the newest proto changes
            - git submodule update --init --remote
        status:
            - test -d packages/proto/src/proto

    install:
        deps:
            - "install:submodules"
        cmds:
            - pnpm i > /dev/null

    build:
        deps:
            - install
        cmds:
            - npx pbjs -r hashgraph -t static-module -w es6 --force-long --no-beautify --no-convert --no-delimited --no-verify -o src/proto.js src/proto/*/**.proto
            - npx pbts -n hashgraph -o src/proto.d.ts src/proto.js
            - perl -pi -e "s#(?<!api\.)proto\.#hashgraph.proto.#g" src/proto.d.ts
            - task: format
            - task: lint
            - npx babel src -d lib
            - npx copyfiles -u 1 src/index.d.ts src/proto.d.ts lib/ > /dev/null
            # This is necessary to correctly run browser tests with an unpublished proto package
            - npx yalc publish > /dev/null

    clean:
        cmds:
            - rm -rf node_modules

    format:
        cmds:
            - npx prettier "*.json" "src/*.js" --write > /dev/null

    lint:
        deps:
            - "lint:types"
            - "lint:format"
            - "lint:js"

    "lint:types":
        cmds:
            - npx tsc

    "lint:format":
        cmds:
            - npx prettier "*.json" "src/*.js" --check > /dev/null

    "lint:js":
        cmds:
            - npx eslint --fix "src/*.js"

    "test:release":
        deps:
            - build

    update:
        cmds:
            - cd src/proto && git pull origin main && git checkout main
            - task: build

    publish:
        preconditions:
            - "! grep '\".*\": \"\\(link\\|file\\):.*\"' package.json > /dev/null"
        deps:
            - "test:release"
        cmds:
            - pnpm publish {{.CLI_ARGS}}
