export PATH := "./node_modules/.bin:" + env_var('PATH')

default:
    @just --choose

install:
    pnpm i

build: install format lint

lint: lint-types lint-format lint-js

lint-types:
    tsc

lint-format:
    prettier "*.js" --check > /dev/null

lint-js:
    eslint --fix "*.js"

format:
    prettier "*.js" --write > /dev/null

clean:
    rm -rf node_modules
