name: Hedera Services Main

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache pnpm modules
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - name: Set up Node 12
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2

      - name: Set up JDK 12
        uses: actions/setup-java@v2
        with:
          java-version: '12'
          distribution: 'adopt'

      - name: Fetch Hedera Services
        uses: actions/checkout@v2
        with:
          repository: hashgraph/hedera-services
          path: hedera-services

      - name: Build Hedera Services
        run: |
          cd hedera-services
          git tag MASTER
          echo "TAG=MASTER" >> .env
          docker build -t services-node:MASTER .
          cd ..

      - name: Fetch Hedera SDK
        uses: actions/checkout@v2
        with:
          path: hedera-sdk-js

      - name: Run Hedera SDK Tests
        env:
          OPERATOR_KEY: "302e020100300506032b65700422042091132178e72057a1d7528025956fe39b0b847f200ab59b2fdd367017f3087137"
          OPERATOR_ID: "0.0.2"
          HEDERA_NETWORK: "localhost"
        run: |
          cd hedera-services
          docker-compose up &
          sleep 45
          cd ../hedera-sdk-js
          pnpm install
          pnpm test:integration:node
